Repository Techeer-Hogwarts/nest, pull requests merged in 2025-02, with the labels that each got.

#53 fix: 서브 도메인 쿠키 공유 설정
  src/auth/auth.controller.ts
Labels: 🛠️ FIX

#51 fix: 프로젝트, 스터디 API 변경사항 수정 완료
  docker-compose.yml
  prisma/migrations/20241124150709_init/migration.sql
  prisma/migrations/20241213051907_1213/migration.sql
  prisma/migrations/20241230094734_1230/migration.sql
  prisma/migrations/20250205130727_0205/migration.sql
  prisma/migrations/20250215164733_project_like/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/auth/auth.controller.ts
  src/modules/projectMembers/dto/request/add.projectMember.request.ts
  src/modules/projectMembers/repository/projectMember.repository.ts
  src/modules/projectTeams/dto/request/create.projectTeam.request.ts
  src/modules/projectTeams/dto/request/get.team.query.request.ts
  src/modules/projectTeams/dto/request/update.projectTeam.request.ts
  src/modules/projectTeams/dto/response/get.projectTeam.response.ts
  src/modules/projectTeams/projectTeam.controller.ts
  src/modules/projectTeams/projectTeam.service.ts
  src/modules/projectTeams/repository/projectTeam.repository.ts
  src/modules/projectTeams/test/mock-data.ts
  src/modules/projectTeams/test/projectTeam.controller.spec.ts
  src/modules/projectTeams/test/projectTeam.repository.spec.ts
  src/modules/projectTeams/test/projectTeam.service.spec.ts
  src/modules/studyTeams/dto/response/get.studyTeam.response.ts
  src/modules/studyTeams/repository/studyTeam.repository.ts
  src/modules/studyTeams/studyTeam.controller.ts
  src/modules/studyTeams/studyTeam.service.ts
  src/modules/studyTeams/test/mock-data.ts
  src/modules/studyTeams/test/studyTeam.controller.spec.ts
  src/modules/studyTeams/test/studyTeam.repository.spec.ts
  src/modules/studyTeams/test/studyTeam.service.spec.ts
Labels: ✨ FEAT, 🛠️ FIX

#56 refactor: 블로그 viewCount 증가 api 추가 및 변경사항 수정 (Like, Bookmark, Resume, Blog)
  prisma/schema.prisma
  prisma/seed.ts
  src/auth/auth.controller.ts
  src/modules/blogs/blog.controller.ts
  src/modules/blogs/blog.service.ts
  src/modules/blogs/dto/request/get.blog.query.request.ts
  src/modules/blogs/dto/response/get.blog.response.ts
  src/modules/blogs/repository/blog.repository.ts
  src/modules/blogs/test/blog.repository.spec.ts
  src/modules/blogs/test/mock-data.ts
  src/modules/bookmarks/bookmark.controller.ts
  src/modules/bookmarks/bookmark.service.ts
  src/modules/bookmarks/dto/response/get.bookmark.response.ts
  src/modules/bookmarks/repository/bookmark.repository.ts
  src/modules/likes/like.controller.ts
  src/modules/likes/like.service.ts
  src/modules/likes/repository/like.repository.ts
  src/modules/likes/test/like.repository.spec.ts
  src/modules/projectTeams/dto/response/get.projectTeamList.response.ts
  src/modules/resumes/dto/request/get.resumes.query.request.ts
  src/modules/resumes/repository/resume.repository.ts
  src/modules/resumes/resume.controller.ts
  src/modules/resumes/test/mock-data.ts
  src/modules/resumes/test/resume.repository.spec.ts
  src/modules/studyTeams/dto/response/get.studyTeamList.response.ts
  src/modules/users/test/user.service.spec.ts
  src/modules/users/user.service.ts
Labels: ✨ FEAT, 🛠️ FIX, 🚀 REFACTOR

#67 fix: 세션에서 키워드 삭제
  src/modules/sessions/dto/request/get.session.query.request.ts
  src/modules/sessions/repository/session.repository.ts
  src/modules/sessions/test/mock-data.ts
  src/modules/sessions/test/session.repository.spec.ts
Labels: 🛠️ FIX

#70 feat: 스택 조회 API 구현
  src/modules/stacks/dto/response/get.stack.response.ts
  src/modules/stacks/repository/stack.repository.ts
  src/modules/stacks/stack.controller.ts
  src/modules/stacks/stack.service.ts
  src/modules/stacks/test/mock-data.ts
  src/modules/stacks/test/stack.controller.spec.ts
  src/modules/stacks/test/stack.repository.spec.ts
  src/modules/stacks/test/stack.servie.spec.ts
Labels: ✨ FEAT

#82 fix: 프로젝트, 스터디 수정사항 반영
  src/modules/projectTeams/dto/response/get.projectTeam.response.ts
  src/modules/studyMembers/entities/studyMember.entity.ts
  src/modules/studyMembers/repository/studyMember.repository.ts
  src/modules/studyTeams/dto/response/get.studyTeam.response.ts
  src/modules/users/repository/user.repository.ts
Labels: 🛠️ FIX

#83 feat: 블로그 삭제 구현완료
  src/modules/blogs/blog.controller.ts
  src/modules/blogs/blog.service.ts
  src/modules/blogs/repository/blog.repository.ts
Labels: ✨ FEAT

#88 fix: 세션 API 토큰 추가
  src/modules/sessions/session.controller.ts
Labels: 🛠️ FIX

#89 fix: 프로젝트api 수정사항 반영
  src/modules/projectMembers/repository/projectMember.repository.ts
  src/modules/projectTeams/dto/request/update.projectTeam.request.ts
  src/modules/projectTeams/projectTeam.controller.ts
  src/modules/projectTeams/projectTeam.service.ts
  src/modules/studyMembers/repository/studyMember.repository.ts
  src/modules/studyTeams/studyTeam.service.ts
Labels: 🛠️ FIX

#90 fix: 프로젝트 수정사항 반영
  src/modules/projectTeams/projectTeam.service.ts
Labels: 🛠️ FIX

#91 fix: 프로젝트& 스터디 리더로직, image 로직 수정
  src/modules/projectTeams/projectTeam.controller.ts
  src/modules/projectTeams/projectTeam.service.ts
  src/modules/studyTeams/studyTeam.controller.ts
  src/modules/studyTeams/studyTeam.service.ts
Labels: 🛠️ FIX

#92 feat: 인덱스 추가 구현 (세션 조회, 좋아요 설정, 블로그 삭제 시)
  src/global/index/index.service.ts
  src/modules/blogs/repository/blog.repository.ts
  src/modules/likes/repository/like.repository.ts
  src/modules/projectTeams/projectTeam.service.ts
  src/modules/sessions/session.service.ts
Labels: ✨ FEAT

#94 fix: 프로젝트&스터디 생성시 리더 로직 수정
  src/global/exception/custom.exception.ts
  src/modules/projectTeams/projectTeam.controller.ts
  src/modules/projectTeams/projectTeam.service.ts
  src/modules/studyTeams/studyTeam.service.ts
Labels: 🛠️ FIX

#95 fix: 세션 썸네일 타입 수정 및 자료 옵션으로 수정
  prisma/migrations/20250222171558_session/migration.sql
  prisma/schema.prisma
  src/modules/sessions/dto/request/create.session.request.ts
  src/modules/sessions/dto/request/update.session.request.ts
  src/modules/sessions/entities/session.entity.ts
Labels: 🛠️ FIX

#96 feat: 이벤트 인덱스 업데이트 url 추가
  src/modules/events/dto/request/index.event.request.ts
Labels: 🛠️ FIX

#101 fix: 팀 조회 필터링 fullstack 추가
  src/modules/projectTeams/projectTeam.service.ts
Labels: 🛠️ FIX

#102 fix: 이력서 목록 조회 필터링 로직 수정
  src/modules/resumes/repository/resume.repository.ts
  src/modules/resumes/test/resume.repository.spec.ts
Labels: 🛠️ FIX

#104 fix: 프로젝트 상세조회시 userId, year 추가
  src/modules/projectTeams/dto/response/get.projectTeam.response.ts
  src/modules/projectTeams/projectTeam.service.ts
Labels: 🛠️ FIX

#105 fix: 프로젝트 팀원 추가 로직 수정
  src/modules/projectTeams/projectTeam.service.ts
Labels: 🛠️ FIX

#106 fix: 이력서 좋아요/북마크 목록 조회 필터링 로직 수정
  src/modules/bookmarks/repository/bookmark.repository.ts
  src/modules/likes/repository/like.repository.ts
  src/modules/projectTeams/dto/request/get.team.query.request.ts
Labels: 🛠️ FIX

#111 fix: 가나다순 정렬 및 이력서 필수로 수정
  src/modules/blogs/repository/blog.repository.ts
  src/modules/blogs/test/blog.repository.spec.ts
  src/modules/projectTeams/projectTeam.service.ts
  src/modules/resumes/repository/resume.repository.ts
  src/modules/resumes/test/resume.repository.spec.ts
  src/modules/sessions/repository/session.repository.ts
  src/modules/sessions/test/session.repository.spec.ts
  src/modules/users/repository/user.repository.ts
  src/modules/users/user.service.ts
Labels: 🛠️ FIX
